### ISSUE TITLE
Make `maxRetries` configurable

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#104]
# Clarification and motivation

In #88, we added support for handling 429 responses and retrying requests. We have a hardcoded limit of `maxRetries = 20`.

We should make this configurable.

# Acceptance criteria

`maxRetries` can be configured through a config file, and overridden via a CLI option.

**Comment by breakerzirconia** [comment]
I'll also make sure to add a certain 429-error-handling test case, discussed [here](https://github.com/serokell/xrefcheck/pull/88#discussion_r749398664), in `Test.Xrefcheck.TooManyRequestsSpec` after implementing the configurability of `maxRetries`.
