### ISSUE TITLE
Traversal vs Scanning

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#119]
# Clarification and motivation

It seems we used the terms "traversal" and "scan" in the documentation/config/source code to refer to the same thing (the act of reading files from disk and parsing its references).

We should settle on one of those terms, and make sure it's used throughout the entire codebase consistently. I suggest we settle on "scan".

**Note**: do not bother renaming the `traversal` yaml key, as this key will be deleted in #170 

https://github.com/serokell/xrefcheck/blob/31777f72ccbe1f6ffea4d8088eaff1c75fb56af4/src/Xrefcheck/Config/Default.hs#L17

# Acceptance criteria

* Any references to "traversal" have been renamed appropriately.

**Comment by Sorokin-Anton** [comment]
@dcastro I wanted to add documentation changes on top of https://github.com/serokell/xrefcheck/tree/Sereja313/%23170-reorganize-config-keys and found that I shouldn't change anything.

The only place where we use `traverse` or words withs ame root is documentation of `forConcurrentlyCaching`, and for me it's correct here

So I think this issue should be closed

**Comment by dcastro** [comment]
@Sorokin-Anton Yup, you're right, good catch! I'll tag #175 with this issue number, so that this issue will be closed when that PR is merged.
