### ISSUE TITLE
Update repos using xrefcheck 0.2.2

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#148]
# Clarification and motivation

After releasing 0.2.2, let's go through some of the active serokell repos and update them to use this latest version.

@Sereja313 
- [x] https://github.com/serokell/universum/pull/276
- [x] https://github.com/serokell/coffer/pull/132
- [x] https://github.com/serokell/tzbot/pull/15
- [x] https://github.com/serokell/tasty-hunit-compat/pull/3

@Sorokin-Anton 
- [x] https://github.com/serokell/tztime/pull/1
- [x] https://github.com/serokell/o-clock/pull/138
- [x] https://github.com/serokell/nyan-interpolation/pull/19
- [x] https://github.com/serokell/uncaught-exception/pull/2

@krendelhoff2 @DMozhevitin @alios
- [x] https://gitlab.com/morley-framework/morley/-/merge_requests/1256
- [x] https://gitlab.com/morley-framework/morley-infra/-/merge_requests/10
- [x] https://gitlab.com/morley-framework/morley-ledgers/-/merge_requests/70
- [x] https://gitlab.com/morley-framework/morley-metadata/-/merge_requests/44
- [x] https://gitlab.com/morley-framework/morley-multisig/-/merge_requests/34
- [x] https://gitlab.com/morley-framework/morley-upgradeable/-/merge_requests/23
- [x] https://gitlab.com/morley-framework/local-chain/-/merge_requests/28/
- [x] https://gitlab.com/morley-framework/indigo/-/merge_requests/44
- [x] https://gitlab.com/morley-framework/morley-debugger/-/merge_requests/76
- [x] https://github.com/tqtezos/stablecoin/pull/202
- [x] https://github.com/tezos-commons/baseDAO/pull/342
- [x] https://github.com/tezos-commons/homebase-lite/pull/35
- [x] https://github.com/tz-wrapped/tezos-btc/pull/182

# Acceptance criteria

The packages above are all using xrefcheck 0.2.2

**Comment by dcastro** [comment]
@Sorokin-Anton @Sereja313 I've assigned the first 6 projects above to you two.
Please go through them, update xrefcheck to 0.2.2, and open PRs in their respective projects.

Edit the issue description above with links to the respective PRs.

@krendelhoff2, @DMozhevitin and @alios will update the tezos-related projects (see [TM-662](https://issues.serokell.io/issue/TM-662))

Folks, please refer to the migration guides at the bottom of the release pages:
* Migrating from 0.2 to 0.2.1: https://github.com/serokell/xrefcheck/releases/tag/v0.2.1
* Migrating from 0.2.1 to 0.2.2: https://github.com/serokell/xrefcheck/releases/tag/v0.2.2

Unfortunately, we don't have migration guides for older versions :/

**Comment by dcastro** [comment]
@Sorokin-Anton @Sereja313 I had forgotten about `tasty-hunit-compat` and `uncaught-exception`. I assigned one to each of you.

**Comment by dcastro** [comment]
`xrefcheck-action` is now fixed.

**Comment by dcastro** [comment]
@alios: Looks like the last 4 PRs have been approved, feel free to merge them ^^

**Comment by Martoon-00** [comment]
@alios How is it going? I see that at least some of those PR seem green and can be merged.

Do you have any blockers? Or this just takes time?

**Comment by alios** [comment]
@dcastro @Martoon-00 Sorry did not saw the emails ... will finalize / merge the missing

**Comment by Martoon-00** [comment]
For the record: I'm also switching LIGO repository to this new version:
- [ ] https://gitlab.com/ligolang/ligo
