### ISSUE TITLE
Improve `ignore link` annotation

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#150]
# Clarification and motivation

At the moment, when we encounter a `<!-- xrefcheck: ignore link -->` annotation, `Xrefcheck.Scanners.Markdown.removeIgnored` skips nodes until we:
1. find a link
2. find another ignore annotation, in which case we throw an error
3. reach the end of the file, in which case we also throw an error

The reason why we skip nodes is that the link node does _not_ have to come right after the annotation node. For example, there might be some text in-between the annotation node and the link node.

E.g., in this case, the annotation node is followed by a paragraph node, with 2 children: one text node and one link node.

```md
<!-- xrefcheck: ignore link-->
Serokell [web-site](https://serokell.io/)
```

There might also be some emphasis or bold nodes as well.

```md
<!-- xrefcheck: ignore link -->
Another ignore link bug _some [link1](link1) emphasis_.
```

However, I would argue the current behavior is too lax, I don't think these scenarios should be allowed:

```md
<!-- xrefcheck: ignore link-->

## Some header

Text [link](file.md).
```

```md
<!-- xrefcheck: ignore link-->

First paragraph.

Second paragraph [link](file.md).
```

More generally, I think a `ignore link` annotation should only look for a link right next to it OR in the children of the node right next to it.

# Acceptance criteria

* We throw an error when an `ignore link` annotation is not followed by a link node OR a node containing a link node in its subtree.

**Comment by Sorokin-Anton** [comment]
@dcastro When there is text like `Check <!-- xrefcheck: ignore link --> our site [a](b)`, should we report this as error? 
Your description in acceptance criteria says it's incorrect, because next node will be `TEXT " our site "` without any children

**Comment by dcastro** [comment]
That's a very good point!

I would add the following exception then: if we're currently visiting a `PARAGRAPH` node and we find an `ignore link` annotation node, then we'll look for a link in any sibling node and their descendants (informally, we'll look for a link from this point until the end of the paragraph).

**Comment by dcastro** [comment]
(and when we're not visiting a `PARAGRAPH` node, we'll look for a link only **in the next** sibling and its descendants)

**Comment by dcastro** [comment]
Actually - let's not overcomplicate this. I can't think of a reason why a user would want/need to place the annotation far away from the link within a paragraph. 

Let's stick to the original rule: the link must be the next sibling node or in one of its descendants.
Using the previous example, the user should rewrite it to:

```md
Check our site <!-- xrefcheck: ignore link --> [a](b)
```

This means we might break some of the existing tests (which is okay, the whole point of this issue is to restrict the "power" of this annotation anyway). We should also check the examples in the readme and fix them as needed.

**Comment by Sorokin-Anton** [comment]
So, you rewrited it to `Check our site <!-- xrefcheck: ignore link --> [a](b)`, and in this case node after annotation will be `TEXT " "`. Of course we can omit space here, but I would prefer old behaviour to this

**Comment by dcastro** [comment]
Oh good catch!

Okay hmm, we've got two options then:

1. Use the general rule only, but also skip empty text nodes and `SOFTBREAK` nodes.
2. Use the general rule and also the [exception](https://github.com/serokell/xrefcheck/issues/150#issuecomment-1261945040) when visiting a paragraph node.

I'm okay with either one.

> but I would prefer old behaviour to this

I take it you prefer option (2) then?

**Comment by Sorokin-Anton** [comment]
Yes, I will try to implement (2)
