### ISSUE TITLE
[BUG] Do not interpret footnotes as links

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#155]
# Description

Original discussion: https://github.com/serokell/xrefcheck/issues/79#issuecomment-1252132762

The Haskell library `cmark-gfm` does not support the "footnotes" commonmark extension, and simply parses them as as ["shortcut reference links"](https://github.github.com/gfm/#shortcut-reference-link) (which have the same syntax as footnotes, except the "link label" component is not necessarily prefixed by a caret `^`).

E.g., this:

```md
Here is footnote[^1]

 [^1]: abc
```

Is parsed as a `LINK` node:

```hs
    [ Node
        ( Just
            ( PosInfo
                { startLine = 1
                , startColumn = 1
                , endLine = 1
                , endColumn = 20
                }
            )
        ) PARAGRAPH
        [ Node
            ( Just
                ( PosInfo
                    { startLine = 1
                    , startColumn = 1
                    , endLine = 1
                    , endColumn = 16
                    }
                )
            )
            ( TEXT "Here is footnote" ) []
        , Node
            ( Just
                ( PosInfo
                    { startLine = 1
                    , startColumn = 17
                    , endLine = 1
                    , endColumn = 20
                    }
                )
            )
            ( LINK "abc" "" )
            [ Node
                ( Just
                    ( PosInfo
                        { startLine = 1
                        , startColumn = 18
                        , endLine = 1
                        , endColumn = 19
                        }
                    )
                )
                ( TEXT "^1" ) []
            ]
        ]

```

This causes `xrefcheck` to verify whether `"abc"` is a link, and thus fail.

HOWEVER, [GitHub's official C implementation](https://github.com/github/cmark-gfm#installing) does support a `footnotes` extension, which, when enabled, interprets footnotes correctly:

```
$ cmark-gfm --list-extensions

Available extensions:
footnotes
table
strikethrough
autolink
tagfilter
tasklist

$ printf 'Here is footnote[^1]

 [^1]: abc' | cmark-gfm -t html --extension footnotes

<p>Here is footnote<sup class="footnote-ref"><a href="#fn-1" id="fnref-1" data-footnote-ref>1</a></sup></p>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>abc <a href="#fnref-1" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```

The Haskell library (which wraps around the C lib using FFI) supports the [other 5 extensions](https://hackage.haskell.org/package/cmark-gfm-0.2.4/docs/CMarkGFM.html#v:extStrikethrough), but not the footnotes extension.
We should open an issue in their repo requesting support for this.

Once the haskell lib supports this, we can able the footnotes extension in xrefcheck.

# To Reproduce

```
$ mkdir demo && cd demo
$ echo "[^1]\n\n [^1]: abc" > a.md
$ xrefcheck

=== Invalid references found ===                                                                                                                    

  ➥  In file a.md
     bad reference (relative) at src:1:1-4:
       - text: "^1"
       - link: abc
       - anchor: -
     
     ⛀  File does not exist:
        abc
     
     
Invalid references dumped, 1 in total.
```

# Expected behavior

Expected xrefcheck to treat "abc" as a text and not as a link, and thus not report any invalid references.

# Environment

* master 91483fcc9ddae252df0ab78e41ae3b7b081c255a

# Additional context

**Comment by Sorokin-Anton** [comment]
Created https://github.com/kivikakk/cmark-gfm-hs/issues/26

**Comment by dcastro** [comment]
Great job @Sorokin-Anton! :clap: 

Your PR has been merged, so now we can (temporarily) pull `cmark-gfm-hs` from their git repo and enable this option in xrefcheck. When a hackage release is made, we'll switch back to fetching it from hackage.

**Comment by Sorokin-Anton** [comment]
Ok, will do this and test that links inside footnotes are checked (because syntax tree will be different)
