### ISSUE TITLE
Add option to disable output coloring

### ISSUE THREAD

**Issue by Sorokin-Anton** [serokell/xrefcheck#185]
# Clarification and motivation
When I need to save output of xrefcheck to file (for example to make a golden test), I need to run `xrefcheck | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" &> expected.gold`, or otherwise I will see something like

```
  ➥  In file [2m[1mdir1/dir2/d2f1.md[0m[0m
     bad reference ([92mcurrent file[0m) [2mat src:9:1-18[0m:
```
This charactrs specify color of text, if it is printed to terminal, but sometimes we want to save output, so I think coloring should be optional

# Acceptance criteria
There is CLI option to disable coloring of xrefcheck output

**Comment by dcastro** [comment]
Good idea, then we can also simplify the `prepare` function in `tests/golden/helpers.bash`

**Comment by Sorokin-Anton** [comment]
> Good idea, then we can also simplify the prepare function in tests/golden/helpers.bash
I don't see how (since we don't want to turn this option on in all tests manually)

**Comment by dcastro** [comment]
> I don't see how (since we don't want to turn this option on in all tests manually)

That's what I was thinking of doing :sweat_smile: But yeah, it wouldn't necessarily be a good tradeoff in terms of effort, so it's fine either way.

**Comment by Sorokin-Anton** [comment]
@diogo I was trying to solve this issue today, there are multiple ways and I don't like any:

1. Coloring is made inside `Buildable` instances, so we can make not `instance Buildable ScanError` but `instance Buildable (WithColoringConfig ScanError)` or something like this (e.g. `Data.Reflection.Given ColoringMode => instance Buildable ScanError`).

2. We can use `unsafePerformIO (readIORef ...)` in this instances, since this flag is either off or on and is unchanged 

3. Instead of prevent coloring, we can remove it afterwards. It can be done with, for example, regex library that support replacements

Maybe you can suggest something (e.g. say that `unsafePerformIO`  or `Given` is fine here)

**Comment by dcastro** [comment]
I prefer option (1). I would like to avoid `unsafePerformIO` for the usual reasons, and removing control sequences after the fact could be error-prone and sounds like a bit of a crutch.

`WithColoringConfig a` is a good idea, but `Given` is even better! With `WithColoringConfig` we'd have to wrap/unwrap `a` a lot, and keep it wrapped in data fields, which would be annoying. `Given` moves this concern completely to the `Buildable` instances, let's go with that.

**Comment by dcastro** [comment]
One more thing: When `--no-color` is _not_ set, but the terminal doesn't support coloring, we should disable coloring anyway.

The `pretty-terminal` lets us do this check with [`supportsPretty`](https://hackage.haskell.org/package/pretty-terminal-0.1.0.0/docs/System-Console-Pretty.html#v:supportsPretty).

In tests, we can simulate this by exporting the environment variable `TERM=dumb` (which is a kind of convention to tell applications that the current terminal does not support coloring).

Please do this in _separate_ commit in the same PR (to keep things easy to review). Or even a separate PR, if you prefer.
