### ISSUE TITLE
Retry on response timeout

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#217]
# Clarification and motivation

When we hammer a service like `github.com`, it _usually_ starts replying with `429 Too Many Requests`. `xrefcheck` knows how to handle that.

However, other times, we may also start getting `Reponse timeout`.

```
=== Invalid references found ===

  ➥  In file README.md
     bad reference (external) at src:22:10-83:
       - text: "latest release"
       - link: https://github.com/tezos-commons/baseDAO/releases/latest
       - anchor: -
     
     ⛂  Response timeout
     
     
     
  ➥  In file README.md
     bad reference (external) at src:51:155-233:
       - text: "our tezos-packaging repository"
       - link: https://github.com/serokell/tezos-packaging
       - anchor: -
     
     ⛂  Response timeout
```

This happens often enough to make the CI fail at an annoying rate.

I think we should handle retries on timeout.

Let's also add a config option in `.xrefcheck.yaml` for specifying how many times to retry on timeouts. A default value of `1` seems sensible enough.

# Acceptance criteria

* By default, `xrefcheck` retries a link (once) when it times out.
* The number of retries is configurable in `.xrefcheck.yaml` (NB: it can be set to 0)

**Comment by Martoon-00** [comment]
Given the described issue, retries on `Response timeout` seems like something that we must have.

However, if we apply this simple solution, another use case will suffer: if I have a small repository with a few links, and one of the links dies and starts reporting `Response timeout`, that will double the verification time. If I had 1-minute timeout, now it would be 2 minutes.

Maybe enable the retry only when for the same domain we have already got at least one `429 Too many requests`? This seems like a good heuristic to me.
