### ISSUE TITLE
Revise styling of the output

### ISSUE THREAD

**Issue by Martoon-00** [serokell/xrefcheck#226]
# Clarification and motivation

Look at the [readme](https://github.com/serokell/xrefcheck#readme), at how the output looks like.

This is all subjective, but there are things that feel like a bad design of the style:
* Names of bad files are given in gray, and they should on contrary stand out.
* Those `-` before `text`, `link`, and `anchor` look redundant, especially after #202.

Let's discuss all this and apply some fixes before the release.

# Acceptance criteria
* Some feedback on the styling is gathered.
* Concrens are discussed.
* On concerns we agreed upon - adjustements in the code are made.

**Comment by aeqz** [comment]
Some other things that we have recently detected:

- We should review the indentation in some error cases. For example, the `AnchorDoesNotExist` similar anchors indentation seems to be excessive.
- The redirect chain error formatting decreases readability. We can try showing in gray the indication attached at the end of a redirect chain (`^-- Some text`).

**Comment by aeqz** [comment]
The `ExternalResourceSomeError` output seems too verbose:

```
  ➥  In file scripts/TranslationsScript/translations/PHPExcel/Documentation/markdown/Overview/01-Getting-Started.md
     bad reference (external) at src:55:4-88:
       - text: "http://www.ecma-international.org/news/TC45_current_work/TC45_available_docs.htm"
       - link: http://www.ecma-international.org/news/TC45_current_work/TC45_available_docs.htm

     ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "www.ecma-international.org", service name: Just "80"): does not exist (nodename nor servname provided, or not known)

  ➥  In file scripts/TranslationsScript/translations/PHPExcel/Documentation/markdown/ReadingSpreadsheetFiles/01-File-Formats.md
     bad reference (external) at src:24:500-579:
       - text: "http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=office#technical"
       - link: http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=office
  
  ➥  In file scripts/TranslationsScript/translations/PHPExcel/Documentation/markdown/ReadingSpreadsheetFiles/01-File-Formats.md
     bad reference (external) at src:24:664-706:
       - text: "http://xml.openoffice.org/general.html"
       - link: http://xml.openoffice.org/general.html

     ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "xml.openoffice.org", service name: Just "80"): does not exist (nodename nor servname provided, or not known)

  ➥  In file scripts/TranslationsScript/translations/PHPExcel/Documentation/markdown/ReadingSpreadsheetFiles/01-File-Formats.md
     bad reference (external) at src:32:291-360:
       - text: "http://projects.gnome.org/gnumeric/doc/file-format-gnumeric.shtml"
       - link: http://projects.gnome.org/gnumeric/doc/file-format-gnumeric.shtml

     ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = 0.0.0.0:0, addrCanonName = Nothing}, host name: Just "projects.gnome.org", service name: Just "80"): does not exist (nodename nor servname provided, or not known)
```

It currently uses the [HttpExceptionContent](https://hackage.haskell.org/package/http-client-0.7.13.1/docs/Network-HTTP-Client.html#t:HttpExceptionContent)'s `Show` instance. Maybe we could try to pattern match on it and show a human friendly message, at least for the most common exception cases.

**Comment by Martoon-00** [comment]
Never seen such long error message there before, we really need to provide custom error message for cases like that :+1:
