### ISSUE TITLE
[BUG] Xrefcheck lacks coloring when it is desired

### ISSUE THREAD

**Issue by Martoon-00** [serokell/xrefcheck#237]
# Description

Today I noticed that in GitLab CI we [do not show](https://gitlab.com/ligolang/ligo/-/jobs/3459805009) colorized output despite apparently it is supported there.

We have to investigate what's going on.

I might believe that GitLab CI can provide `TERM=dumb` that causes `coloringSupported = False` in our code; if this is the case and we understand that this is unavoidable and not some weird behaviour of their CI, then perhaps we should add a flag to force-enable coloring. We have to think about all this.

# Environment

- 0.2.2 version

# Additional context

**Comment by aeqz** [comment]
[supportsPretty ](https://hackage.haskell.org/package/pretty-terminal-0.1.0.0/docs/src/System-Console-Pretty.html#supportsPretty) seems to check that `TERM` is not `dumb`, and also that `stdout` is connected to a terminal.

As you pointed out, `TERM=dumb` in GitLab CI, but changing the environment variable value does not enable coloring, so I tried the following within a GitLab CI script:

```sh
$ if [ -t 1 ] ; then echo "terminal"; else echo "not a terminal"; fi
not a terminal
$ if [[ -p /dev/stdout ]] ; then echo "pipe"; else echo "not a pipe"; fi
pipe
$ if [[ ! -t 1 && ! -p /dev/stdout ]] ; then echo "redirection"; else echo "not a redirection"; fi
not a redirection
```

It suggests that GitLab passes each script command output through a pipe.

Adding a flag to force coloring seems easy to implement and a good fit for this case. We could name it `color`, as Xrefcheck already has a `no-color` option that disables coloring, so the result would be:

* `--no-color`: disables it.
* `--color`: forces it.
* None of this flags: check with `supportsPretty`.

which is pretty similar as it currently does for showing the progress bar:

* `--no-progress`: disables it.
* `--progress`: forces it.
* None of this flags: check with `askWithinCI `.

**Comment by aeqz** [comment]
Another option, if we want it to work out of the box, is to also use `askWithinCI` and show colors in this case.

**Comment by Martoon-00** [comment]
Nice investigation :+1: 

Let's probably have all the features you mentioned here:
* Check `askWithinCI`.
* If `askWithinCI` returns `False`, I think it makes sense to use the default `supportsPretty` behaviour, it is quite optimal for local runs.
* Optionally: still add `--color` flag that overrides our guesses. E.g. my Emacs terminal also has `TERM=dumb`, but probably for its own reasons, coloring is supported there.
