### ISSUE TITLE
[BUG] Failure with NoResponseDataReceived

### ISSUE THREAD

**Issue by Martoon-00** [serokell/xrefcheck#280]
# Description

In `ligo` repository `xrefcheck` currently fails for one link:

```
  ➥  In file vendored-dune/Preprocessor/README.md
     bad reference (external) at src:517:1-107:
       - text: "minimal module system"
       - link: https://ligolang.org/docs/language-basics/modules
       - anchor: modules-and-imports-build-system
     
     ⛂  NoResponseDataReceived
```

and I see no reasons for that link to be considered invalid.

# To Reproduce

1. Create a document with `https://ligolang.org/docs/language-basics/modules` link.
2. Run `xrefcheck`

# Expected behavior

The check passes.

# Environment

- OS: LIGO CI ([pipeline](https://gitlab.com/ligolang/ligo/-/jobs/4046550777))
- Version: 0.2.2

**Comment by dcastro** [comment]
Why is `NoResponseDataReceived` only happening for that particular link though?

The [docs](https://hackage.haskell.org/package/http-client-0.7.13.1/docs/Network-HTTP-Client.html#v:NoResponseDataReceived) say this:

> No response data was received from the server at all. This exception may deserve special handling within the library, since it may indicate that a pipelining has been used, and a connection thought to be open was in fact closed.

So it looks like a connection issue (which would imply that xrefcheck was unable to check whether the link is valid or not, so it's inconclusive).
