### ISSUE TITLE
Invert --no-progress

### ISSUE THREAD

**Issue by gromakovsky** [serokell/xrefcheck#42]
# Clarification and motivation

By default `xrefcheck` reports progress by printing some nice progress bars. That's a cool feature when you run this tool on your computer but it's usually quite useless on CI. And CI often doesn't handle progress bars well, it doesn't update it in place, rather prints multiple bars (that depends on particular CI system of course).

Since according to our vision the primary use-case for `xrefcheck` is CI, it seems better to disable progress reporting by default. And replace `--no-progress` with `--progress` with the opposite semantics.

# Acceptance criteria

1. Progress reporting is disabled by default.
2. There is no `--no-progress`.
3. There is `--progress` that enables the existing progress reporting.

**Comment by Martoon-00** [comment]
Mmm, on the one hand, I understand the justification for this change and it would make sense if CI was the primary use case, but on the other hand, I also want to have a smooth experience with local runs very much, and it won't work well with this change :/
1. Usually you write script for CI once, and can run locally multiple times, but passing `--progress` each time is tiresome.
2. I bet most people won't even notice that `--progress` option exists.

**Comment by Martoon-00** [comment]
Let me see whether we can see from Haskell whether the terminal supports backtracking, maybe `--no-progress` won't be necessary for most CIs.

**Comment by Martoon-00** [comment]
Actually no, I tried looking at `TERM` env variable and `hIsTerminalDevice`, and they do not reveal the difference between normal terminal and github actions' one.

Though both github actions and buildkite have `CI=true` variable :thinking:

**Comment by gromakovsky** [comment]
We've discussed this issue and decided to have both `--progress` and `--no-progress` and deduce default behavior from the `CI` variable. If it's set to `true` (case-insensitive) or `1` (or maybe any positive number), progress reporting is disabled by default. Otherwise it's enabled.

Note that in theory one may specify both. We can prohibit it or pick one deterministically (e. g. the last one).
