### ISSUE TITLE
Flakification

### ISSUE THREAD

**Issue by notgne2** [serokell/xrefcheck#54]
# Clarification and motivation

We would like to use this project from inside various other using flakes, this is technically already possible, though without replacing Niv with Nix flakes inside this project, we will not be able to override inputs.

We also generally use Nix flakes as a standard in all of our new projects, and it would be nice for this one to be modernized too.

# Acceptance criteria

- [ ] Niv has been removed
- [ ] The project has moved the main entrypoint to a purely evaluatable `flake.nix`
- [ ] a `default.nix` and potentially `shell.nix` have been provided using `flake-compat` for compatibility

**Comment by balsoft** [comment]
Relevant: https://github.com/serokell/xrefcheck/tree/flake

**Comment by rvem** [comment]
Done in #258
