### ISSUE TITLE
Dump all the errors from different files

### ISSUE THREAD

**Issue by alyoanton9** [serokell/xrefcheck#56]
# Clarification and motivation

As we have right in-place annotations now (`<!-- xrefcheck: ignore <mode>-->`), there can be broken markdowns.
For example:
1. `<!-- xrefcheck: ignore file-->` located in the "middle" of the file (not right after the comments at the top) causes `Error when scanning .\markdowns\with-annotations\no_paragraph.md: expected a PARAGRAPH after "ignore paragraph", but found HEADING (9:1-17)`.
2. A typo like `<!-- xrefcheck: ignore ile -->` causes `Error when scanning .\markdowns\with-annotations\unexpected_ignore_file.md: unrecognised option " "ignore ile" perhaps you meant <"ignore link"|"ignore paragraph"|"ignore file"> ( 9:1 - 8:0)`
And so on.

Currently, `xrefcheck` fails immediately after the first observed error because `die` is used right in `markdownScanner`:
```
markdownScanner path = do
    errOrInfo <- parseFileInfo . decodeUtf8 <$> BSL.readFile path
    case errOrInfo of
        Left errTxt -> do
            die $ "Error when scanning " <> path <> ": " <> T.unpack errTxt
        Right fileInfo -> return fileInfo
```
And propagated on a higher level, to `Main`.
What we want is dumping all the errors from different markdowns and then print them as a final `xrefcheck`'s result together with the broken links.
A possible solution is to add a custom exception type for scanner errors, this way exceptions can be reasonably caught outside if necessary (not in inner components).

# Acceptance criteria

1. No `die` in inner components.
2. All the errors are printed as a result together with the broken links.

**Comment by dcastro** [comment]
@Sereja313: Andrii had previously started working on this issue. He had a Draft PR (see #87). I'm not sure how close to completion it was - can you please have a look at the PR?

Let me know what you think of the PR, and whether you think it's best to just continue working on that branch (it's been a while, rebasing that branch might lead to lots of merge conflicts) or to start from scratch with your own approach.

**Comment by Sereja313** [comment]
@dcastro, It looks like he was only at the beginning of the work and not much was done, so I started from scratch to avoid merge conflicts.

**Comment by dcastro** [comment]
@Sereja313 Sounds goods! :+1:
