### ISSUE TITLE
[BUG] Fix the detection of the broken code style reference: `docs/code-style.md`

### ISSUE THREAD

**Issue by breakerzirconia** [serokell/xrefcheck#86]
# Description

A reference to the code style guide -- `docs/code-style.md` -- at the end of the [pull request template](.github/pull_request_template.md) appears to be broken; however, it seems to bypass `xrefcheck`'s repository traversal, as it doesn't classify the said reference as broken.

# Acceptance criteria

1. The faulty link is expected to be dumped by `xrefcheck`.
2. Its **valid** counterpart -- `/docs/code-style.md` --  is expected to stay valid under `xrefcheck`'s verification.

**Comment by Martoon-00** [comment]
Ugh sad, they seem to break this from time to time.

Currently `xrefcheck` intentionally ignores the file with the pull request template (as can be seen in config), because links appearing in the pull request description have their own rules (they do not start from the repository root, and they have to mention `master` branch), and these rules seem to change more often than we publish new releases.

I'm not sure how can we keep this properly up-to-date. Though, it may be a suitable time to finally try to come up with some solution.

**Comment by breakerzirconia** [comment]
Oh, that seems to explain an interesting thing I've observed when having dealt with the issue! I have once pushed a certain change onto my local [issue #75 branch](https://github.com/serokell/xrefcheck/pull/82) to test whether a CI build would break if given a different, _broken_ link at the exact same place where the style guide link is placed (that test change no longer exists, for I've retracted that respective commit shortly after); it was something like `/docs/broken-link.md`. The CI build would **pass**! Considering what you've written, that behavior _would_ make sense, because xrefcheck ignores the PR template markdown file, right?

**Comment by Martoon-00** [comment]
> Oh, that seems to explain an interesting thing I've observed when having dealt with the issue! I have once pushed a certain change onto my local [issue #75 branch](https://github.com/serokell/xrefcheck/pull/82) to test whether a CI build would fail if given a different, _broken_ link at the exact same place where the style guide link is placed (that test change no longer exists, for I've retracted that respective commit shortly after); it was something like `/docs/broken-link.md`. The CI build **passed**! Considering what you've written, that behavior _would_ make sense, because xrefcheck ignores the PR template markdown file, right?

_I'm sorry for the late reply._

Yes, PR template file is ignored, so it's quite likely that you've hit exactly this behaviour, I think everything is fine.


Mm, not sure how this happened, but currently most of those links are wrong (despite they look right). Say, the PR template file contains the link to the style guide as `/docs/style.md`. This would be fully valid if we considered the PR template file as part of our markdown documentation, but it is not; instead we want the links in PRs to be rendered correctly, but that iink to the style guide actually refers to `https://github.com/docs/code-style.md` in all of our PRs, and this does not make sense, we have to make some corrections into this.

**Comment by dcastro** [comment]
@Martoon-00 Oh, so, to sum up:

In `.github/pull_request_template.md`, `/` refers to `github.com`, 
whereas in every other markdown file `/` refers to the project root? Ok that's weird..

**Comment by Martoon-00** [comment]
When the link from a template is pasted to PR, it starts referring to weird places, yeah
